- name: Create cerfiticates folder if it does not exist
  file:
    path: "{{ loggly.certificate_dest }}"
    state: directory

- name: Install Loggly Certificate Bundle
  get_url:
    url: "{{ loggly.certificate_url }}"
    dest: "{{ loggly.certificate_dest }}{{ loggly.certificate_file }}"
  notify:
    - restart_rsyslog

- name: Find Existing Loggly Artifacts
  find:
    paths: /etc/rsyslog.d
    patterns: '*-loggly-*'
  register: loggly_artifacts

- name: Cleanup Existing Artifacts Left From Previous Installations
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ loggly_artifacts.files }}"

- name: Ensure Application Logfiles Exist
  file:
    path: "{{ item }}"
    state: touch
    follow: yes
  with_items: "{{ loggly.application.logs }}"

- name: Add Rsyslog configuration file
  template:
    src: "{{ item }}"
    dest: "/etc/rsyslog.d/{{ item }}"
    owner: root
    group: root
  with_items:
    - 21-loggly-base.conf
    - 22-loggly-application.conf
    - 22-loggly-nginx.conf
    - 23-loggly-rsyslog_tls.conf
  notify:
    - restart_rsyslog
