- name: Create cerfiticates folder if it does not exist
  file:
    path: "{{ loggly.certificate_dest }}"
    state: directory

# using shell until file: state=absent works the same as below
- name: Cleanup files that may have been left by other installations
  shell: rm -f /etc/rsyslog.d/*-loggly-*

- name: Add Rsyslog configuration file
  template:
    src: "{{ item }}"
    dest: "/etc/rsyslog.d/{{ item }}"
    owner: root
    group: root
  with_items:
    - 21-loggly-base.conf
    - 22-loggly-application.conf
    - 22-loggly-nginx.conf
    - 23-loggly-rsyslog_tls.conf
  notify:
    - restart_rsyslog
