- name: Install logrotate
  apt:
    pkg: logrotate
    state: present

- name: update f5 logrotate config
  template:
    src: logrotate.f5
    dest: /etc/logrotate.d/f5
    owner: root
    group: root

- name: add rotation to daily cron
  template:
    src: logrotate.cron
    dest: /etc/cron.daily/logrotate
    owner: root
    group: root
