---
- apt: name=rsyslog-gnutls update_cache=yes

- name: Create cerfiticates folder If It Does Not Exist
  file: path={{ loggly.certificate_dest }} state=directory

- name: Install loggly certificate bundle once https://en.wikipedia.org/wiki/Server_Name_Indication is supported
  get_url: url={{ loggly.certificate_url }} dest={{ loggly.certificate_dest }}{{ loggly.certificate_file }}
  ignore_errors: yes
  
- name: Use wget cause Python 2.7.6 doesn't support https://en.wikipedia.org/wiki/Server_Name_Indication
  command: wget -O {{ loggly.certificate_dest }}{{ loggly.certificate_file }} {{ loggly.certificate_url }}
  notify:
    - restart_rsyslog

- name: Add Rsyslog configuration file
  template: src="{{ item }}" dest="/etc/rsyslog.d/{{ item }}" owner=root group=root
  with_items:
    - 22-loggly.conf
  notify:
    - restart_rsyslog    
