---
- fail: msg="This role requires 'loggly.token'"
  when: loggly.token | trim == ''

# Only supported by Ubuntu targets - will provide support for $InputFileName wilcard paths
# - apt_repository: repo='{{ loggly.rsylog_ppa }}'
#- debug: msg="PPA is {{ loggly.rsylog_ppa }}"
#  when: loggly.rsylog_ppa

- apt: name={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - rsyslog-gnutls
    - wget

- name: Create cerfiticates folder If It Does Not Exist
  file: path={{ loggly.certificate_dest }} state=directory

- name: Install loggly certificate bundle once https://en.wikipedia.org/wiki/Server_Name_Indication is supported
  get_url: url={{ loggly.certificate_url }} dest={{ loggly.certificate_dest }}{{ loggly.certificate_file }}
  ignore_errors: yes
  
- name: Use wget cause Python 2.7.6 doesn't support https://en.wikipedia.org/wiki/Server_Name_Indication
  command: wget -O {{ loggly.certificate_dest }}{{ loggly.certificate_file }} {{ loggly.certificate_url }}
  notify:
    - restart_rsyslog

- name: Add Rsyslog configuration file
  template: src="{{ item }}" dest="/etc/rsyslog.d/{{ item }}" owner=root group=root
  with_items:
    - 22-loggly.conf
    - 21-nginx-loggly.conf
    - 21-rails.conf
  notify:
    - restart_rsyslog
