- name: Install Rsyslog custom PPA for a consistent version
  apt_repository:
    repo: "{{ loggly.rsyslog_ppa }}"

- name: Install Rsyslog with TLS
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - rsyslog
    - rsyslog-gnutls

- name: Disable $KLogPermitNonKernelFacility configuration (this option is deprecated)
  lineinfile:
    dest: /etc/rsyslog.conf
    state: absent
    regexp: '^\$KLogPermitNonKernelFacility'
