- name: Install Rsyslog custom repository for v8 on Ubuntu <= 14.04
  apt_repository:
    repo: "{{ loggly.rsyslog_apt_repository }}"
    state: present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version|float < 16.04

- name: Cleanup older apt repositories on Ubuntu > 14.04
  apt_repository:
    repo: "{{ loggly.rsyslog_apt_repository }}"
    state: absent
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version|float >= 16.04

- name: Install Rsyslog with TLS
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - rsyslog
    - rsyslog-gnutls

- name: Disable $KLogPermitNonKernelFacility configuration (this option is deprecated)
  lineinfile:
    dest: /etc/rsyslog.conf
    state: absent
    regexp: '^\$KLogPermitNonKernelFacility'
